DJango/carpool/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', include('logPage.urls')),
    path("login/", include("logPage.urls")),
    path("home/", include("homePage.urls")),
    path('ride/', include('ride.urls')),
    path('schedule/', include('schedule.urls')),
    path('history/', include('history.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', LoginView.as_view(template_name='logPage/login.html'), name='login'),
]

DJango/logPage/urls.py
from django.urls import path
from . import views


app_name = 'logPage'


urlpatterns = [
    path('', views.index, name="index"),
    path('register.html', views.register, name="register"),
    path('forgot-password.html', views.forget, name="forget"),
    path('registerUser/', views.addUser, name="registerUser"),
    path('verifyUser/', views.verifyUser, name="authenticate"),
]

DJango/ride/urls.py
from django.urls import path
from . import views

app_name = 'ride'


urlpatterns = [
    path('book-ride/', views.ride_booking_view, name='book_ride'),
    path('api/submit/', views.submit_ride_request, name='submit_ride_request'),
    path('api/status/', views.check_ride_status, name='check_ride_status'),
]

DJango/logPage/models.py
from django.db import models

DJango/logPage/forms.py
from django import forms

# class NameForm(forms.Form):
#    	userId = models.CharField(max_length = 200 , label = 'userId')
# 	passWd = models.CharField(max_length = 200 , label = 'passWd')
# 	firstName = models.CharField(max_length = 200 , label = 'firstName')
# 	lastName = models.CharField(max_length = 200 , label = 'lastName')

DJango/logPage/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import authenticate, login

# Create your views here.
# from .models import user


def index(request):
    return render(request, "login.html", {})


def register(request):
    print("-----------REGISTER---------------")
    context = {'userExist': False}
    return render(request, "register.html", context)


def forget(request):
    return render(request, "forgot-password.html", {})


def validateForm(input):
    if User.objects.filter(username=input['userId']).exists():
        return True
    else:
        user = User.objects.create_user(
            username=input['userId'], email='fake@gmail.com', password=input['passWd'])
        # Update fields and then save again
        user.first_name = firstName = input['firstName']
        user.last_name = lastName = input['lastName']
        user.save()
        return False


def addUser(request):
    context = {'userExist': False}
    if request.method == "POST":
        if validateForm(request.POST) == True:
            context['userExist'] = True
            return render(request, "register.html", context)
    return render(request, "login.html", {})


def verifyUser(request):
    context = {'loginFail': False, 'userExist': True}
    if request.method == "POST":
        try:
            userni = User.objects.get(username=request.POST["userId"])
            user = authenticate(
                request, username=request.POST["userId"], password=request.POST["passWd"])
            print(user)
            if user is None:
                context['loginFail'] = True
                return render(request, "login.html", context)
            else:
                login(request, user)
                return redirect('homePage:home')
        except:
            context['userExist'] = False
            return render(request, "login.html", context)

DJango/logPage/templates/drive_or_ride.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HitchRide - Choose</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <!-- <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> 
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div> -->
              <!-- <div class="col-lg-13"> -->
                <div class="p-5"style="margin: auto;">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">SELECT YOUR OPTION</h1>
                  </div>
                  <form class="user">
                    <a href="{% url 'driver:driverHome' %}" class="btn btn-primary btn-user btn-block">
                      Opt for drive
                    </a>
                    <hr>
                    <a href="{% url 'rider:ride' %}" class="btn btn-primary btn-user btn-block">
                      Book a ride
                    </a>
                  </form>
                  <hr>
                </div>
              <!-- </div> -->
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

DJango/logPage/templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HitchRide - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="login.html">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

DJango/logPage/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HitchRide - Login</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 130px;
      }
    </style>
</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form action="{% url 'logPage:authenticate' %}" name = "authenticate" method = "post" class= "user">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name = "userId" id="userId" placeholder="Enter User Id">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name = "passWd" id="passWd" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Login">
                    <hr>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'logPage:register' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
</body>

</html>

DJango/logPage/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HitchRide Register</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

   <style>
    .img-container {
      text-align: center;
      display: block;
      position: relative;
      top: 130px;
    }
  </style>

</head>

<body class="bg-gradient-primary">
  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block">
            <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
            </span>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form action="{% url 'logPage:registerUser' %}" name = "registration"  onsubmit = "return validateForm()" method = "post" class="user">
                 {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" name = "firstName" id="firstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" name ="lastName" id="lastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control form-control-user"  name ="userId" id="userId" placeholder="User Id">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" name ="passWd" id="passWd" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user"  name = "rpassWd" id="rpassWd" placeholder="Repeat Password">
                  </div>
                </div>
                  <input type="submit" class="btn btn-primary btn-user btn-block" value="OK">
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'logPage:index' %}">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script>
    function validateForm() {
    var val = document.forms["registration"]["firstName"].value;
    if (val == "") {
        alert("First Name can't be empty");
        return false;
      }
      var val = document.forms["registration"]["lastName"].value;
      if (val == "") {
        alert("Last Name can't be empty");
        return false;
      }
      var val = document.forms["registration"]["userId"].value;
      if (val.length < 6) {
        alert("userID should be at least 6 characters long");
        return false;
      }
      var val1 = document.forms["registration"]["passWd"].value;
      var val2 = document.forms["registration"]["rpassWd"].value;

      if(val1 != val2) {
        alert("Passwords not matching");
        return false;
      }
  
      if(val1.length < 6) {
        alert("Password should be at least 6 characters long");
        return false;
      }
  } 
  </script>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
  {% if userExist %}
   <script> alert("User Id already exists!") </script>
  {% endif %}

</body>

</html>